# Generated by Django 3.2.9 on 2021-11-14 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('image_token', models.CharField(default='none', max_length=30)),
            ],
        ),
    ]
