# Generated by Django 3.2.7 on 2021-11-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
