# Generated by Django 3.2.7 on 2021-11-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
    ]
