# Generated by Django 3.2.7 on 2021-11-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_profile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='author_email',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
