# Generated by Django 3.2.9 on 2021-11-20 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='author_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_token',
            field=models.CharField(max_length=30),
        ),
    ]
